version: 2

sources:
  - name: raw_data
    description: "BIRD_DATA_DB"
    database: BIRD_DATA_DB
    schema: RAW_DATA
    tables:
      - name: OCCURRENCES_RAW
        description: "Raw bird occurrence data."