name: CI

on:
  pull_request:
    branches:
      - master

  push:
    branches:
      - dev
      - master

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Ruff
        uses: astral-sh/ruff-action@v3
        with:
          args: check .


  dbt-parse:
    name: dbt Parse
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create .env
        run: |
          cat > .env <<EOF
          SNOWFLAKE_ACCOUNT=${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER=${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD=${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_ROLE=${{ secrets.SNOWFLAKE_ROLE }}
          SNOWFLAKE_WAREHOUSE=${{ secrets.SNOWFLAKE_WAREHOUSE }}
          BIRD_DATA_DB=${{ secrets.BIRD_DATA_DB }}
          EOF

      - name: Build code location image
        run: docker compose build code_location

      - name: Run dbt parse
        run: >
          docker compose run --rm
          code_location
          dbt parse


  dagster-check:
    name: Dagster Definitions Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create .env
        run: |
          cat > .env <<EOF
          SNOWFLAKE_ACCOUNT=${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER=${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD=${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_ROLE=${{ secrets.SNOWFLAKE_ROLE }}
          SNOWFLAKE_WAREHOUSE=${{ secrets.SNOWFLAKE_WAREHOUSE }}
          BIRD_DATA_DB=${{ secrets.BIRD_DATA_DB }}
          EOF

      - name: Build code location image
        run: docker compose build code_location

      - name: Check Dagster definitions
        run: >
          docker compose run --rm
          code_location
          dagster
          definitions
          validate
          -m
          dagster_project.definitions